language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t syedhusyn/work-flow -f Dockerfile.dev .

script:
  # -- --coverage allows the container to shutdown after test
  - docker run -e CI=true syedhusyn/work-flow npm run test -- --coverage

deploy:
  # travis supports elasticbeanstalk on its own
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-102499425438"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
